import 'dart:convert';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

import '../errors/auth_errors.dart';
import 'apple_sign_in.dart' show kAuthStubMode, fakeJwtForStub;

// ---------------------------------------------------------------------------
// Stub guard — same mechanism as apple_sign_in.dart
// ---------------------------------------------------------------------------
//
// When AUTH_MODE=stub, returns a fake OAuthCredential without calling the
// real GoogleSignIn plugin. Remove the stub once T-v0.6-C01 (Firebase project
// + OAuth client IDs) is fully configured.

/// Singleton GoogleSignIn client.
///
/// Injectable for testing — pass a custom [GoogleSignIn] instance via the
/// factory in [AuthService] if you need to override the client ID.
GoogleSignIn _defaultGoogleSignIn() => GoogleSignIn(
      scopes: ['email', 'profile'],
      // Client IDs are taken from the firebase_options.dart generated by
      // `flutterfire configure`. On Android the google-services.json takes
      // precedence; on iOS / Web the clientId field below is required.
      // clientId: FirebaseOptions.currentPlatform.iosClientId,
      //
      // TODO(T-v0.6-C01): uncomment and populate clientId once
      // firebase_options.dart exists.
    );

/// Obtains an [OAuthCredential] via Google Sign-In.
///
/// Returns `null` if the user cancelled the sign-in UI.
/// Throws a typed [AuthError] for all other failure modes.
///
/// [googleSignIn] is injectable for unit testing; defaults to a real
/// [GoogleSignIn] instance.
Future<OAuthCredential?> getGoogleCredential({
  GoogleSignIn? googleSignIn,
}) async {
  if (kAuthStubMode) {
    return _stubGoogleCredential();
  }
  return _realGoogleCredential(googleSignIn ?? _defaultGoogleSignIn());
}

// ---------------------------------------------------------------------------
// Real path
// ---------------------------------------------------------------------------

Future<OAuthCredential?> _realGoogleCredential(GoogleSignIn client) async {
  try {
    // If there is already a signed-in account, sign out first to avoid
    // returning a silently-cached session from a previous call — the caller
    // always wants an explicit, fresh sign-in gesture.
    await client.signOut();

    final account = await client.signIn();
    if (account == null) {
      // User dismissed the picker — not an error.
      return null;
    }

    final auth = await account.authentication;
    if (auth.idToken == null) {
      throw AuthProviderError(
        'Google Sign-In succeeded but returned no idToken.',
        providerCode: 'missing_id_token',
      );
    }

    return GoogleAuthProvider.credential(
      idToken: auth.idToken,
      accessToken: auth.accessToken,
    );
  } on AuthProviderError {
    rethrow;
  } catch (e) {
    // google_sign_in does not expose a stable exception hierarchy across
    // platforms, so we catch broadly and wrap.
    final msg = e.toString().toLowerCase();
    if (msg.contains('network') || msg.contains('io_error')) {
      throw AuthNetworkError('Network error during Google Sign-In', e);
    }
    throw AuthProviderError(
      'Google Sign-In failed: $e',
      cause: e,
    );
  }
}

// ---------------------------------------------------------------------------
// Stub path
// ---------------------------------------------------------------------------

OAuthCredential _stubGoogleCredential() {
  return GoogleAuthProvider.credential(
    idToken: fakeJwtForStub('google-stub-user', 'https://accounts.google.com'),
    accessToken: 'stub-access-token',
  );
}
